### ISSUE TITLE
Long-term goal: open deployment

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring#113] opened 2018-08-23 18:59 UTC
I just sat through a very interesting talk by Yuvi Panda, formerly of WikiMedia ops, now working for Jupyter. He has led the deployment of [mybinder.org](http://mybinder.org), a free and open scientific computing infrastructure. They practice radically open deployment that "rhymes" well with EDGI values:
- Their [deployment configuration](https://github.com/jupyterhub/mybinder.org-deploy ) is completely open. Only the secret tokens are encrypted.
- Their live [monitoring](http://grafana.mybinder.org) is completely open.
- Their [operating costs](https://github.com/jupyterhub/binder-data) are completely open.
- They do blameless post-mortems of outages and produce incident reports and a guide designed to empower any team member to debug deployments and resolve outages. The guide and the reports are [open to the public]( https://mybinder-sre.readthedocs.io/en/latest/) too:
- They use Kubernetes to avoid vendor lock-in. It is important for open projects to treat cloud services as commodities; open standards like Kubernetes enable this. (I am reminded of [this recent, short blog post](http://matthewrocklin.com/blog/work/2018/08/19/cloud-lockin-and-open-standards) on that subject.) This also enables the service to be deployed in countries where US cloud providers are not accessible.

The deployments are co-managed by about 5 contributors. Of that team, Yuvi is the only one with ops experience. None have deployment/ops as their primary responsibility. The main source of downtime is waiting for someone to have time to handle an outage. (This sounds like us.) Because their deployment configuration is open, anyone can contribute a PR, whether or not they have credentials. When a PR to the deploy repo is merged, the new configuration is deployed to staging, automatically tested there, and deployed to production only if everything works. This is the established standard in industry but rare in community projects. This takes significant upfront work (mainly to eliminate false-positive test failures, they say) but runs with little maintenance.

Given the up-front work involved, I don't think this is a realistic short-term goal for EDGI, but I think it is an inspiring long-term goal. This scheme aligns well with our values of openness, accessibility, and  accountability --- whether we grow one large, shared deployment or many separately-managed deployments.

cc @dcwalk @Mr0grog @lightandluck @jsnshrmn

**Comment by Mr0grog** [comment] 2018-08-29 19:32
Neat! I’m curious to see this talk if it was recorded and ever makes its way online. I also don’t think this goal is really (or at least doesn’t need to be) all that far away. :)

> Their deployment configuration is completely open. Only the secret tokens are encrypted.

I think your intention was to make ours open as soon as they’re working, right? (We should make sure to start a new repo and not a fork, though, just so we don’t have to worry about anything that might have been hard-coded in the history.)

> Their live monitoring is completely open.

I don’t think I have any concerns with this in principle, though I’m not really sure it makes sense to maintain our own monitoring infra. And if we used a service, it’s probably not easy to make public.

> Their operating costs are completely open.

👍 but I think we’d have to work with EDGI steering committee on this.

> They do blameless post-mortems of outages and produce incident reports

Maybe I’ve been assuming that people don’t have a lot of extra time to commit to postmortems, but we could totally do that. I probably *should* be writing incident reports, though. I guess I’ve been seeing this as mostly a dialog with myself (outside of times something significant enough has happened for me to note it in meetings) since basically all the server management and the vast majority of the code has fallen on me at this point.

> They use Kubernetes to avoid vendor lock-in.

I don’t think this is a good reason for using Kubernetes, but I also don’t have anything against Kubernetes. :P

We’ve got a working deployment and continuous image publishing that we’ve always said we could use if the Ansible work didn’t wind up seeming like a better alternative. Either way, though, I’m not sure this part is all that important in terms of open or portable practices.

> When a PR to the deploy repo is merged, the new configuration is deployed to staging, automatically tested there, and deployed to production only if everything works.

I don’t think this is a big step at all! We already automatically build and publish docker images automatically when PRs merge. (Well, almost: I made it so you have to click an approve button, so if you merge several dependency update PRs in a row, you don’t wind up with a deploy for each of them; also, I’d really appreciate it if other people logged in and clicked that instead of leaving it to me when they merge a PR!) The only question here is whether the tests in staging are manual or automated smoke tests (we don’t have any of those, and I’m not sure spending much time on automating this part is worthwhile for us at our scale).

**Comment by dcwalk** [comment] 2018-08-30 03:16
Super neat @danielballan :) (also hi!hi! been too long)

Also, somewhat randomly I also heard a little bit about mybinder.org 's open deployment at an open scholarship meeting a few weeks ago! I was really interested in how they coordinate it, so thank you for this detailed info.

Way out of scope, but I'm going to ping @jevi-me who is thinking about reproducible deployments for TRU right now, as this may be of some interest

**Comment by Mr0grog** [comment] 2018-09-05 20:54
>> Maybe I’ve been assuming that people don’t have a lot of extra time to commit to postmortems, but we could totally do that.

> The ones I see from mybinder.org look like a fairly low-key summary written up by the people who handled the issue, not much more effort than the updates that currently get posted in our Slack --- just maintained in a structured, persistent, and discoverable medium.

Cool. Let’s start doing this in the `edgi-govdata-archiving/web-monitoring` repo for now (i.e. this repo) until we have a public deployment repo. (Hopefully in two weeks! 🤞) I’ll make an `incidents` folder here with a README.

> Neat! I think I'm missing something -- where is this "approve" button?

It’s annoyingly buried. You have to go to “workflows” → [click a project] and you’ll see a workflow listed with “on hold” as its status:

![screen shot 2018-09-05 at 1 44 22 pm](https://user-images.githubusercontent.com/74178/45120149-2b5f6580-b112-11e8-97c9-ffa1d6ddc025.png)

Then you click the workflow (or the “on hold” block) to see the workflow details, then click the “hold” block in the workflow diagram:

![screen shot 2018-09-05 at 1 46 22 pm](https://user-images.githubusercontent.com/74178/45120489-1fc06e80-b113-11e8-9911-510136c8c2c6.png)

That’ll pop up a dialog where you can click “approve”:

![screen shot 2018-09-05 at 1 46 26 pm](https://user-images.githubusercontent.com/74178/45120178-403bf900-b112-11e8-8adc-fde6dd471791.png)

Canceling the flow is easy, though. You can just click the “cancel” button in the list of workflows. ¯\\\_(ツ)\_/¯

No idea why they haven’t made that easier or implemented an e-mail alert that you can just click to approve. Also auto-expiring workflows on hold. All those are highly requested improvements in their tracker, but have stayed that way with no action for the better part of the year.

It’s enough of a bear that I’ve been considering switching to some kind of scheduled job that checks for updates to master and auto publishes once or twice a day or something. My original concern was that we’d want some kind of safety valve on publishing, but now I’m just concerned about rapid-fire publishes when we merge a bunch of dependabot PRs in a row (especially if they come out of order because different builds take different amounts of time).

**Comment by Mr0grog** [comment] 2018-09-05 21:00
(Other alternative: have a `publish` or `deploy` branch that we publish from [instead of master], and manually merge master onto it to cause Circle to publish from that branch.)

**Comment by danielballan** [comment] 2019-03-05 20:47
I still think this is interesting and worth keeping open as a long-term goal.

**Comment by Mr0grog** [comment] 2019-09-03 01:28
So…

- We now have the ops repo: https://github.com/edgi-govdata-archiving/web-monitoring-ops
- We automatically build releases whenever someone pushes to the `release` branch on our code repos.
- @danielballan is working on tracking public metrics in edgi-govdata-archiving/web-monitoring-db#505

Can we turn this issue into something more concrete? What other stuff do we want to make happen here?

**Comment by Mr0grog** [comment] 2019-10-23 01:44
Per the above comment, I’m going ahead and closing this. We can open more specific issues for anything new.

**Closed by Mr0grog** 2019-10-23 01:44 UTC

**Comment by danielballan** [comment] 2019-10-23 12:45
:+1:
